### ISSUE TITLE
Alternative Idea for Pet/Stance Bars?

### ISSUE THREAD

**Issue by jmgrimes** [ls-/oUF_LS#11]
![pet-stance-alternative](https://cloud.githubusercontent.com/assets/1869138/8356536/fa3c9da6-1b23-11e5-801e-338b7f8dfee3.png)

After fidgeting around a bit, I ended up creating a slightly different config for the death knight class where both a pet and a stance bar are necessary (Unholy).  I'm not sure if other classes are like this (I'm mostly a melee player), but I thought it might be interesting for others.  This could be altered to swap the positions of the pet and stance bars as well.

Anyway:

DEATHKNIGHT = 3,
PET3 = {"BOTTOM", -52, 117},
STANCE3 = {"BOTTOM", 248, 117}

Thanks for all of your work on this.  I've tried MANY layouts, and ultimately, as a melee player, no other layout comes even close to this for making the information I really need accessible and easy to understand.  That giant player resources and health bubble is the best thing ever for tanking.

**Comment by ls-** [comment]
Thanks for kind words!

As for your idea, that's really nice placement, and that's precisely why I implemented frame moving via /lsmovers command, to allow players place things where they want 'em to be.

I guess, I'll add this as an optional preset a bit later, when I get to actionbar ingame config. I'm currently busy with two things: a) fighting my flu; b) auratracker ingame config;
