### ISSUE TITLE
OUF-LS Aura Frames issues

### ISSUE THREAD

**Issue by electricmenace** [ls-/oUF_LS#12]
I keep getting hundreds of these erorrs (below)
I really really like your player frame but I disabled everything else.  

OmniCC is causing this because of the buff icons on the target frame.
The line at 43 attempts to set the text size and I think that is where it bombs out.
I commented that line out and now no errors but no text either :)

Here is the error:

338x oUF_LS\modules\unitframes\elements\auras-Auras.lua:43: attempt to call method 'SetTimerTextHeight' (a nil value)
oUF_LS\modules\unitframes\elements\auras-Auras.lua:43: in function <oUF_LS\modules\unitframes\elements\auras.lua:32>
oUF_LS\embeds\oUF\elements\aura.lua:157: in function <oUF_LS\embeds\oUF\elements\aura.lua:138>
oUF_LS\embeds\oUF\elements\aura.lua:297: in function <oUF_LS\embeds\oUF\elements\aura.lua:291>
oUF_LS\embeds\oUF\elements\aura.lua:402: in function <oUF_LS\embeds\oUF\elements\aura.lua:318>
oUF_LS\embeds\oUF\elements\aura.lua:443: in function `func'
oUF_LS\embeds\oUF\ouf.lua:164: in function <oUF_LS\embeds\oUF\ouf.lua:155>
(tail call): ?

**Comment by ls-** [comment]
Hi! Thank you for your feedback!

Damn, sometimes I simply forget about other addons, and then I get these compatibility issues :(

Fixed this one with 4fa9566788a267c1c717b07fd4cd9f6082343b10.
