### ISSUE TITLE
Shaman Totem timers

### ISSUE THREAD

**Issue by xapher19** [ls-/oUF_LS#4]
Hey, just wanted to let you know that if you have a totem out and it's about to despawn and you use Totemic Recall to despawn it, the timer will freeze on whatever number it was at.
![Here's a screenshot, my water totem wasn't summoned at the time.](https://cloud.githubusercontent.com/assets/3515584/5118893/a19a25d8-7060-11e4-9c4a-7573a1be0a67.jpg)

**Comment by ls-** [comment]
Fixed by df67141c2af9bbdad441e0bdb7b9082346c34fba
Sorry, forgot about it, will be released with v1.3.9 for 6.1.
