### ISSUE TITLE
Original cast bar whilst in vehicle.

### ISSUE THREAD

**Issue by Candlekeeper** [ls-/oUF_LS#5]
If you use abilities with a cast time in vehicles the default cast bar for wow will show up.
In addition the oUF_LS cast bar will also still be there.
Both of them work.

I saw this in the quest "The Talon King" 
I do not know if this is reproducible.

I forgot to take a screenshot, sorry about that. 

I will see if I can find another instance of this issue so I can post it here.

**Comment by ls-** [comment]
Fixed with https://github.com/ls-/oUF/commit/7aff711a9f7f027557b409259dd71019f89623cf
