### ISSUE TITLE
Utilize libdatabroker-1-1 for infobars instead of home grown approach.

### ISSUE THREAD

**Issue by Soulsbane** [ls-/oUF_LS#6]
Add support for [libdatabroker-1-1](https://github.com/tekkub/libdatabroker-1-1) and use the same approach as [LibCargoShip-2.1](https://github.com/xconstruct/LibCargoShip-2.1). Granted, lots of blocks will get messy.

**Comment by ls-** [comment]
@Soulsbane, I'm testing infobars based on LDB now, and I sorta fail to see any profit T_T Internally things became more complicated, plus 3 libs, but the only visible change was that I could add my fps text from infobar to Titan Panel, but... but.. what else? Teach me, sensei! I've never used libs before :D

Anyway, I'm not sure about my infobars future yet, let's say, right now I have location, system info (memory, fps and latency) and clock bars left... I'll write some thought about it on WoWI later..

For now I have other things to do... Unit Frames..

**Comment by Soulsbane** [comment]
Yeah, the more I use oUF_LS the more I think that doing this would be a bad idea.  It looks fine now with just a few blocks.  If someone wants several blocks enabled at once it's going to look pretty bad.

**Comment by ls-** [comment]
Ok then, but I may use LDB in the future, who knows how I'm gonna expand my layout in the future, hehe :3

Could you please read my latest comment on wowi and provide me with some feedback on my thoughts either here or there?
